spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_SAW?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update