spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_SAW?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /SAW-API-docs
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info, health"
info:
  app:
    name: SAW Application
    version: 1.0.0
    description: Website that allows to buy tickets for concerts, festivals or other events.
  author: AmmyB

